"""Unit tests: forensics collision detection + core fingerprint mechanics."""

from copcat.forensics import (scan_source, build_forensics,
                              collision_pairs, apply_forensics_to_pairs)
from copcat.models import Submission, PairResult
from copcat.lexing import lex
from copcat.canon import canonical_tokens
from copcat.normal import fingerprint, containment
from copcat.shadow import fold_comments


def test_scan_source_artifacts():
    src = ('"""\nAutomatically generated by Colab.\n'
           "https://colab.research.google.com/drive/1ABCabcABCabcABCabc\n"
           '"\nfrom IPython.core.completer import back_latex_name_matches\n')
    info = scan_source(src)
    assert info["colab_ids"] == ["1ABCabcABCabcABCabc"]
    assert info["generator"] == "Colab"
    assert info["ipython_artifacts"] is True


def test_notebook_collision_escalates_pair():
    shared = ("https://colab.research.google.com/drive/1ABCabcABCabcABCabc")
    src = "x = 1  # {}\n".format(shared)
    subs = [Submission("A", "a.py", "", src),
            Submission("B", "b.py", "", src),
            Submission("C", "c.py", "", "y = 2\n")]
    fore, coll = build_forensics(subs)
    assert len(coll) == 1 and coll[0][2] == ["A", "B"]
    assert collision_pairs(coll) == {("A", "B")}
    p = PairResult("A", "B", "a.py", "b.py")
    apply_forensics_to_pairs([p], coll)
    assert p.flag == "SUSPICIOUS" and "forensics" in p.evidence[0]
    clean = PairResult("A", "C", "a.py", "c.py")
    apply_forensics_to_pairs([clean], coll)
    assert clean.flag == "CLEAN"


def test_rename_invariance_full_containment():
    code = ("class Stack:\n"
            "    def __init__(self):\n        self.items = []\n"
            "    def push(self, value):\n        self.items.append(value)\n"
            "    def pop(self):\n"
            "        if not self.items:\n            raise IndexError('empty')\n"
            "        return self.items.pop()\n")
    other = (code.replace("Stack", "Pile").replace("items", "elements")
                 .replace("value", "x").replace("push", "add")
                 .replace("pop", "remove"))
    ta, _, _ = canonical_tokens(code)
    tb, _, _ = canonical_tokens(other)
    assert containment(fingerprint(ta, 16, 8), fingerprint(tb, 16, 8)) == 1.0


def test_prose_comments_do_not_fold():
    shadow, strings, code_like, total = fold_comments(
        [(1, "This function calculates the circle area"),
         (2, "returns none for invalid input")])
    assert (shadow, strings, code_like) == ([], [], 0)


def test_code_comments_fold_with_strings():
    pairs = [(1, "class Book: pass"), (2, "b = Book('Clean Code', 2)")]
    shadow, strings, code_like, _ = fold_comments(pairs)
    assert "Book" in shadow and "Clean Code" in strings and code_like == 2
