"""Submission forensics: notebook IDs, generator headers, IPython artifacts.

Student files often carry provenance metadata they forgot to strip — most
commonly the "Automatically generated by Colab" header containing the
Google Drive ID of the source notebook. Two different students sharing one
notebook ID is definitive evidence the same notebook was passed around,
independent of any similarity metric.
"""

import re
from collections import defaultdict

COLAB_RE = re.compile(
    r"colab\.research\.google\.com/drive/([A-Za-z0-9_-]{10,})", re.IGNORECASE)
DRIVE_FILE_RE = re.compile(
    r"drive\.google\.com/(?:file/d|open\?id=)/([A-Za-z0-9_-]{10,})", re.IGNORECASE)
GENERATOR_RE = re.compile(r"Automatically\s+generated\s+by\s+([A-Za-z0-9_ ]+)", re.IGNORECASE)
IPYTHON_RE = re.compile(r"\b(?:from\s+IPython|import\s+IPython|get_ipython\s*\()")
NOTEBOOK_FILE_RE = re.compile(r"\.(ipynb)\b", re.IGNORECASE)


def scan_source(source):
    """Provenance artifacts found in one submission's source text."""
    return {
        "colab_ids": sorted(set(COLAB_RE.findall(source))),
        "drive_ids": sorted(set(DRIVE_FILE_RE.findall(source))),
        "generator": (GENERATOR_RE.search(source).group(1).strip()
                      if GENERATOR_RE.search(source) else None),
        "ipython_artifacts": bool(IPYTHON_RE.search(source)),
        "notebook_refs": bool(NOTEBOOK_FILE_RE.search(source)),
    }


def build_forensics(subs):
    """Scan all submissions; return (per_roll_info, collisions).

    collisions: list of (artifact_type, artifact_id, [rolls...]) where the
    same notebook/drive ID appears in more than one submission.
    """
    per_roll = {}
    owners = defaultdict(set)   # ("colab", id) -> {rolls}
    for s in subs:
        info = scan_source(s.source)
        per_roll[s.roll] = info
        for nid in info["colab_ids"]:
            owners[("colab-notebook", nid)].add(s.roll)
        for nid in info["drive_ids"]:
            owners[("drive-file", nid)].add(s.roll)

    collisions = []
    for (kind, nid), rolls in sorted(owners.items()):
        if len(rolls) > 1:
            collisions.append((kind, nid, sorted(rolls)))
    return per_roll, collisions


def collision_pairs(collisions):
    """All roll pairs that share at least one notebook/drive ID."""
    pairs = set()
    for _kind, _nid, rolls in collisions:
        for i in range(len(rolls)):
            for j in range(i + 1, len(rolls)):
                pairs.add((rolls[i], rolls[j]))
    return pairs


def apply_forensics_to_pairs(pairs, collisions):
    """Attach collision evidence to the affected PairResults and escalate
    their flags — a shared notebook ID is definitive regardless of metrics."""
    by_pair = {(min(p.roll_a, p.roll_b), max(p.roll_a, p.roll_b)): p
               for p in pairs}
    for kind, nid, rolls in collisions:
        for i in range(len(rolls)):
            for j in range(i + 1, len(rolls)):
                ra, rb = sorted((rolls[i], rolls[j]))
                p = by_pair.get((ra, rb))
                if p is None:
                    continue
                p.evidence.append(
                    "forensics: both submissions carry the same {} id `{}` "
                    "(same source notebook was shared)".format(kind, nid))
                if p.flag == "CLEAN":
                    p.flag = "SUSPICIOUS"
                    p.blended = max(p.blended, 0.0)  # flag via evidence
    return pairs
